### ISSUE TITLE
Could not find me.2bab:seal:2.0.0.

### ISSUE THREAD

**Issue by Edgar-Dong** [2BAB/Seal#13]
repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'me.2bab:seal:2.0.0'
    }

====================================================

Could not find me.2bab:seal:2.0.0.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/me/2bab/seal/2.0.0/seal-2.0.0.pom
  - https://dl.google.com/dl/android/maven2/me/2bab/seal/2.0.0/seal-2.0.0.jar
  - https://repo.maven.apache.org/maven2/me/2bab/seal/2.0.0/seal-2.0.0.pom
  - https://repo.maven.apache.org/maven2/me/2bab/seal/2.0.0/seal-2.0.0.jar
  - https://jcenter.bintray.com/me/2bab/seal/2.0.0/seal-2.0.0.pom
  - https://jcenter.bintray.com/me/2bab/seal/2.0.0/seal-2.0.0.jar

**Comment by 2BAB** [comment]
Sorry, the 2.0.0 was released on bintray, I didn't migrate it to mavenCentral(). If you do need it can build from the tag [2.0.0](https://github.com/2BAB/Seal/releases/tag/2.0.0). Since AGP 3.0 is deprecated long time ago, and Seal 2.x is not API compatible with 3.x, so I will not work on any issues of 2.x. Will close the issue soon.

**Comment by Edgar-Dong** [comment]
👌🏻
